#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Symfony\Component\Console\Input\ArgvInput;
use WPSP\WPSP;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
//$app = WPSP::instance()->getApplication();
$app = Application::configure(basePath: __DIR__)
        ->withRouting(
                web: __DIR__.'/routes/web.php',
                commands: __DIR__.'/routes/console.php',
                health: '/up',
        )
        ->withMiddleware(function (Middleware $middleware): void {
            //
        })
        ->withExceptions(function (Exceptions $exceptions): void {
            //
        })->create();

$status = $app->handleCommand(new ArgvInput);

exit($status);